/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId])
/******/ 			return installedModules[moduleId].exports;
/******/
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			exports: {},
/******/ 			id: moduleId,
/******/ 			loaded: false
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.loaded = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(0);
/******/ })
/************************************************************************/
/******/ ({

/***/ 0:
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(113)
	var __weex_template__ = __webpack_require__(114)
	var __weex_style__ = __webpack_require__(115)
	var __weex_script__ = __webpack_require__(116)
	
	__weex_define__('@weex-component/1f58900b4cddf9a7923e69da9576b3d8', [], function(__weex_require__, __weex_exports__, __weex_module__) {
	
	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }
	
	    __weex_module__.exports.template = __weex_template__
	
	    __weex_module__.exports.style = __weex_style__
	
	})
	
	__weex_bootstrap__('@weex-component/1f58900b4cddf9a7923e69da9576b3d8',undefined,undefined)

/***/ },

/***/ 90:
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "info-win"
	  ],
	  "children": [
	    {
	      "type": "image",
	      "classList": [
	        "cover"
	      ],
	      "attr": {
	        "src": function () {return this.src}
	      }
	    },
	    {
	      "type": "text",
	      "classList": [
	        "desc"
	      ],
	      "attr": {
	        "value": function () {return this.title}
	      }
	    },
	    {
	      "type": "text",
	      "classList": [
	        "address"
	      ],
	      "attr": {
	        "value": function () {return this.location}
	      }
	    }
	  ]
	}

/***/ },

/***/ 91:
/***/ function(module, exports) {

	module.exports = {
	  "info-win": {
	    "width": 500,
	    "padding": 5,
	    "backgroundColor": "#ffffff",
	    "borderWidth": 1,
	    "borderColor": "rgba(0,0,0,0.1)",
	    "borderBottomWidth": 2,
	    "borderBottomColor": "rgba(0,0,0,0.25)"
	  },
	  "cover": {
	    "flex": 1,
	    "height": 180
	  },
	  "desc": {
	    "fontSize": 20,
	    "backgroundColor": "#ffffff",
	    "padding": 5
	  },
	  "address": {
	    "fontSize": 16,
	    "color": "#999999",
	    "backgroundColor": "#ffffff",
	    "padding": 5,
	    "paddingBottom": 10
	  }
	}

/***/ },

/***/ 92:
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){"use strict";
	
	Object.defineProperty(exports, "__esModule", {
	    value: true
	});
	exports.default = {};}
	/* generated by weex-loader */


/***/ },

/***/ 93:
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "navbar-con"
	  ],
	  "children": [
	    {
	      "type": "div",
	      "classList": [
	        "navbar"
	      ],
	      "children": [
	        {
	          "type": "div",
	          "classList": [
	            "btn-back"
	          ],
	          "events": {
	            "click": "goHome"
	          },
	          "children": [
	            {
	              "type": "image",
	              "classList": [
	                "btn-arrow-left"
	              ],
	              "attr": {
	                "src": "http://img1.vued.vanthink.cn/vued9c8e7e738ff94abee23eb69d7f1401e9.png"
	              }
	            },
	            {
	              "type": "text",
	              "classList": [
	                "btn-text"
	              ],
	              "attr": {
	                "value": "返回"
	              }
	            }
	          ]
	        },
	        {
	          "type": "text",
	          "classList": [
	            "title"
	          ],
	          "attr": {
	            "value": function () {return this.title}
	          }
	        }
	      ]
	    }
	  ]
	}

/***/ },

/***/ 94:
/***/ function(module, exports) {

	module.exports = {
	  "navbar-con": {
	    "height": 98,
	    "paddingTop": 10
	  },
	  "navbar": {
	    "zIndex": 1000,
	    "position": "relative",
	    "display": "flex",
	    "flexDirection": "row",
	    "height": 88,
	    "backgroundColor": "#ffffff",
	    "alignItems": "center",
	    "borderBottomWidth": 2,
	    "borderBottomColor": "#dddddd"
	  },
	  "btn-back": {
	    "zIndex": 1002,
	    "flexDirection": "row",
	    "alignItems": "center",
	    "width": 180,
	    "height": 88
	  },
	  "btn-arrow-left": {
	    "width": 60,
	    "height": 60,
	    "marginLeft": 10
	  },
	  "btn-text": {
	    "color": "#0f89f5"
	  },
	  "title": {
	    "position": "absolute",
	    "left": 180,
	    "right": 180,
	    "top": 0,
	    "height": 88,
	    "lineHeight": 88,
	    "fontSize": 36,
	    "textAlign": "center"
	  }
	}

/***/ },

/***/ 95:
/***/ function(module, exports) {

	module.exports = function(module, exports, __weex_require__){'use strict';
	
	var navigator = __weex_require__('@weex-module/navigator');
	module.exports = {
	  methods: {
	    goHome: function goHome() {
	      navigator.pop();
	    }
	  }
	};}
	/* generated by weex-loader */


/***/ },

/***/ 103:
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(93)
	var __weex_style__ = __webpack_require__(94)
	var __weex_script__ = __webpack_require__(95)
	
	__weex_define__('@weex-component/navbar', [], function(__weex_require__, __weex_exports__, __weex_module__) {
	
	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }
	
	    __weex_module__.exports.template = __weex_template__
	
	    __weex_module__.exports.style = __weex_style__
	
	})


/***/ },

/***/ 113:
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(113)
	var __weex_template__ = __webpack_require__(114)
	var __weex_style__ = __webpack_require__(115)
	var __weex_script__ = __webpack_require__(116)
	
	__weex_define__('@weex-component/info-window', [], function(__weex_require__, __weex_exports__, __weex_module__) {
	
	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }
	
	    __weex_module__.exports.template = __weex_template__
	
	    __weex_module__.exports.style = __weex_style__
	
	})


/***/ },

/***/ 114:
/***/ function(module, exports) {

	module.exports = {
	  "type": "div",
	  "classList": [
	    "container"
	  ],
	  "children": [
	    {
	      "type": "navbar",
	      "attr": {
	        "title": "设置自定义信息窗体"
	      }
	    },
	    {
	      "type": "weex-amap",
	      "classList": [
	        "map"
	      ],
	      "id": "map2017",
	      "attr": {
	        "sdkKey": function () {return this.keys},
	        "zoom": function () {return this.zoom},
	        "center": function () {return this.pos}
	      },
	      "children": [
	        {
	          "type": "weex-amap-marker",
	          "style": {
	            "zIndex": 1000
	          },
	          "attr": {
	            "hideCallout": "true",
	            "position": function () {return this.marker.position},
	            "icon": function () {return this.marker.icon},
	            "title": function () {return this.marker.title}
	          }
	        },
	        {
	          "type": "weex-amap-marker",
	          "style": {
	            "zIndex": 1000
	          },
	          "attr": {
	            "hideCallout": "true",
	            "position": function () {return this.marker2.position},
	            "icon": function () {return this.marker.icon},
	            "title": function () {return this.marker2.title}
	          }
	        },
	        {
	          "type": "weex-amap-info-window",
	          "attr": {
	            "open": function () {return this.palaceMuseum.open},
	            "offset": function () {return this.palaceMuseum.offset},
	            "position": function () {return this.palaceMuseum.position}
	          },
	          "children": [
	            {
	              "type": "info-window",
	              "attr": {
	                "src": "http://img1.vued.vanthink.cn/vued6dfd998fc0738f7e88d4b66bafc547ce.jpeg",
	                "title": "The Palace Museum",
	                "location": "4 Jingshan Front St, Dongcheng Qu, Beijing"
	              }
	            }
	          ]
	        },
	        {
	          "type": "weex-amap-info-window",
	          "attr": {
	            "open": function () {return this.southStation.open},
	            "offset": function () {return this.southStation.offset},
	            "position": function () {return this.southStation.position}
	          },
	          "children": [
	            {
	              "type": "info-window",
	              "attr": {
	                "src": "http://img1.vued.vanthink.cn/vued2de302ef72ae921313a1fa1bbbbd9455.jpeg",
	                "title": "Beijing South Railway Station",
	                "location": "Fengtai, Beijing"
	              }
	            }
	          ]
	        }
	      ]
	    },
	    {
	      "type": "div",
	      "classList": [
	        "map-control"
	      ],
	      "children": [
	        {
	          "type": "text",
	          "classList": [
	            "title"
	          ],
	          "attr": {
	            "value": "Component: weex-amap-info-window"
	          }
	        },
	        {
	          "type": "text",
	          "classList": [
	            "tips"
	          ],
	          "attr": {
	            "value": "在地图上显示自定义窗体"
	          }
	        },
	        {
	          "type": "div",
	          "events": {
	            "click": "toggleMus"
	          },
	          "classList": [
	            "btnbox"
	          ],
	          "children": [
	            {
	              "type": "text",
	              "shown": function () {return !this.palaceMuseum.open},
	              "classList": [
	                "btn"
	              ],
	              "attr": {
	                "value": "打开故宫信息"
	              }
	            },
	            {
	              "type": "text",
	              "shown": function () {return this.palaceMuseum.open},
	              "classList": [
	                "btn"
	              ],
	              "attr": {
	                "value": "关闭故宫信息"
	              }
	            }
	          ]
	        },
	        {
	          "type": "div",
	          "events": {
	            "click": "toggleSta"
	          },
	          "classList": [
	            "btnbox"
	          ],
	          "children": [
	            {
	              "type": "text",
	              "shown": function () {return !this.southStation.open},
	              "classList": [
	                "btn"
	              ],
	              "attr": {
	                "value": "打开南站信息"
	              }
	            },
	            {
	              "type": "text",
	              "shown": function () {return this.southStation.open},
	              "classList": [
	                "btn"
	              ],
	              "attr": {
	                "value": "关闭南站信息"
	              }
	            }
	          ]
	        }
	      ]
	    }
	  ]
	}

/***/ },

/***/ 115:
/***/ function(module, exports) {

	module.exports = {
	  "container": {
	    "position": "relative",
	    "flex": 1,
	    "backgroundColor": "#ffffff"
	  },
	  "map": {
	    "flex": 1,
	    "position": "relative",
	    "backgroundColor": "#ffffff",
	    "minHeight": 800,
	    "borderBottomWidth": 10,
	    "borderBottomColor": "#ffffff"
	  },
	  "map-control": {
	    "paddingTop": 20,
	    "minHeight": 600
	  },
	  "title": {
	    "marginLeft": 20,
	    "paddingLeft": 20,
	    "paddingTop": 10,
	    "paddingBottom": 10,
	    "fontSize": 36,
	    "borderLeftWidth": 6,
	    "borderLeftColor": "#0f89f5",
	    "color": "#222222",
	    "textAlign": "left"
	  },
	  "tips": {
	    "margin": 20,
	    "padding": 10,
	    "color": "#666666",
	    "fontSize": 20
	  },
	  "btn": {
	    "margin": 20,
	    "padding": 20,
	    "backgroundColor": "#1ba1e2",
	    "borderRadius": 5,
	    "color": "#ffffff",
	    "textAlign": "center",
	    "cursor": "pointer",
	    "fontSize": 28
	  }
	}

/***/ },

/***/ 116:
/***/ function(module, exports, __webpack_require__) {

	module.exports = function(module, exports, __weex_require__){'use strict';
	
	__webpack_require__(103);
	__webpack_require__(117);
	var Amap = null;
	try {
	  Amap = __weex_require__('@weex-module/amap');
	} catch (err) {
	  console.log(err);
	}
	var modal = __weex_require__('@weex-module/modal');
	module.exports = {
	  data: function () {return {
	    keys: {
	      h5: 'f4b99dcd51752142ec0f1bdcb9a8ec02',
	      ios: '',
	      android: 'db6a973159cb0c2639ad02c617a786ae'
	    },
	    pos: [116.397428, 39.90923],
	    zoom: 11,
	    marker: {
	      position: [116.379278, 39.865374],
	      title: 'Beijing South Railway Station',
	      icon: 'http://img1.vued.vanthink.cn/vuede8f1ae7b454267d75c31c6d46819b597.png'
	    },
	    marker2: {
	      position: [116.397389, 39.908742],
	      title: 'The Palace Museum',
	      icon: 'http://img1.vued.vanthink.cn/vuede8f1ae7b454267d75c31c6d46819b597.png'
	    },
	    palaceMuseum: {
	      position: [116.397389, 39.908742],
	      offset: [60, -120],
	      open: false
	    },
	    southStation: {
	      position: [116.379278, 39.865374],
	      offset: [60, -120],
	      open: true
	    }
	  }},
	
	  methods: {
	    toggleSta: function toggleSta() {
	      this.southStation.open = !this.southStation.open;
	
	      if (this.southStation.open && this.palaceMuseum.open) {
	        this.palaceMuseum.open = false;
	      }
	    },
	    toggleMus: function toggleMus() {
	      this.palaceMuseum.open = !this.palaceMuseum.open;
	      if (this.palaceMuseum.open && this.southStation.open) {
	        this.southStation.open = false;
	      }
	    }
	  }
	};}
	/* generated by weex-loader */


/***/ },

/***/ 117:
/***/ function(module, exports, __webpack_require__) {

	var __weex_template__ = __webpack_require__(90)
	var __weex_style__ = __webpack_require__(91)
	var __weex_script__ = __webpack_require__(92)
	
	__weex_define__('@weex-component/info-window', [], function(__weex_require__, __weex_exports__, __weex_module__) {
	
	    __weex_script__(__weex_module__, __weex_exports__, __weex_require__)
	    if (__weex_exports__.__esModule && __weex_exports__.default) {
	      __weex_module__.exports = __weex_exports__.default
	    }
	
	    __weex_module__.exports.template = __weex_template__
	
	    __weex_module__.exports.style = __weex_style__
	
	})


/***/ }

/******/ });
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vd2VicGFjay9ib290c3RyYXAgODBkODM0NjI0ODcxNjNhMWZkMTE/NDY0ZCoqKioqKioqKiIsIndlYnBhY2s6Ly8vLi9zcmMvcGFnZXMvaW5mby13aW5kb3cud2U/NTY5YiIsIndlYnBhY2s6Ly8vLi9zcmMvaW5jbHVkZS9pbmZvLXdpbmRvdy53ZT9lNWQ1KiIsIndlYnBhY2s6Ly8vLi9zcmMvaW5jbHVkZS9pbmZvLXdpbmRvdy53ZT9kMzk3KiIsIndlYnBhY2s6Ly8vLi9zcmMvaW5jbHVkZS9pbmZvLXdpbmRvdy53ZT82NmMyIiwid2VicGFjazovLy8uL3NyYy9pbmNsdWRlL25hdmJhci53ZT8zNTYxKioqKioiLCJ3ZWJwYWNrOi8vLy4vc3JjL2luY2x1ZGUvbmF2YmFyLndlPzliNDAqKioqKiIsIndlYnBhY2s6Ly8vLi9zcmMvaW5jbHVkZS9uYXZiYXIud2U/YzE5NioqKioqIiwid2VicGFjazovLy8uL3NyYy9pbmNsdWRlL25hdmJhci53ZT9mODdhKioqKiIsIndlYnBhY2s6Ly8vLi9zcmMvcGFnZXMvaW5mby13aW5kb3cud2U/MzFlZCIsIndlYnBhY2s6Ly8vLi9zcmMvcGFnZXMvaW5mby13aW5kb3cud2U/Yzg0NiIsIndlYnBhY2s6Ly8vLi9zcmMvcGFnZXMvaW5mby13aW5kb3cud2U/YjBhOSIsIndlYnBhY2s6Ly8vLi9zcmMvcGFnZXMvaW5mby13aW5kb3cud2UiLCJ3ZWJwYWNrOi8vLy4vc3JjL2luY2x1ZGUvaW5mby13aW5kb3cud2U/YmY0OSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7QUFDQTs7QUFFQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7QUFFQTtBQUNBO0FBQ0EsdUJBQWU7QUFDZjtBQUNBO0FBQ0E7O0FBRUE7QUFDQTs7QUFFQTtBQUNBOztBQUVBO0FBQ0E7QUFDQTs7O0FBR0E7QUFDQTs7QUFFQTtBQUNBOztBQUVBO0FBQ0E7O0FBRUE7QUFDQTs7Ozs7Ozs7QUN0Q0E7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7O0FBRUE7QUFDQTtBQUNBO0FBQ0E7O0FBRUE7O0FBRUE7O0FBRUEsRUFBQzs7QUFFRCwyRjs7Ozs7OztBQ2xCQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSw2QkFBNEI7QUFDNUI7QUFDQSxNQUFLO0FBQ0w7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsK0JBQThCO0FBQzlCO0FBQ0EsTUFBSztBQUNMO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLCtCQUE4QjtBQUM5QjtBQUNBO0FBQ0E7QUFDQSxFOzs7Ozs7O0FDbENBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLElBQUc7QUFDSDtBQUNBO0FBQ0E7QUFDQSxJQUFHO0FBQ0g7QUFDQTtBQUNBO0FBQ0E7QUFDQSxJQUFHO0FBQ0g7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxFOzs7Ozs7Ozs7Ozs7bUJDYUE7Ozs7Ozs7OztBQ3ZDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLFlBQVc7QUFDWDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxjQUFhO0FBQ2I7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxVQUFTO0FBQ1Q7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsbUNBQWtDO0FBQ2xDO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxFOzs7Ozs7O0FDckRBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsSUFBRztBQUNIO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsSUFBRztBQUNIO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLElBQUc7QUFDSDtBQUNBO0FBQ0E7QUFDQTtBQUNBLElBQUc7QUFDSDtBQUNBO0FBQ0EsSUFBRztBQUNIO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsRTs7Ozs7Ozs7O0FDYUEseUJBQ0E7OzsrQkFHQTtpQkFDQTtBQUVBO0FBSkE7QUFEQTs7Ozs7Ozs7O0FDeERBO0FBQ0E7QUFDQTs7QUFFQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTs7QUFFQTs7QUFFQTs7QUFFQSxFQUFDOzs7Ozs7OztBQ2ZEO0FBQ0E7QUFDQTtBQUNBOztBQUVBOztBQUVBO0FBQ0E7QUFDQTtBQUNBOztBQUVBOztBQUVBOztBQUVBLEVBQUM7Ozs7Ozs7O0FDaEJEO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxNQUFLO0FBQ0w7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxnQ0FBK0IsaUJBQWlCO0FBQ2hELDhCQUE2QixpQkFBaUI7QUFDOUMsZ0NBQStCO0FBQy9CLFFBQU87QUFDUDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsWUFBVztBQUNYO0FBQ0E7QUFDQSxzQ0FBcUMsNEJBQTRCO0FBQ2pFLGtDQUFpQyx3QkFBd0I7QUFDekQsbUNBQWtDO0FBQ2xDO0FBQ0EsVUFBUztBQUNUO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsWUFBVztBQUNYO0FBQ0E7QUFDQSxzQ0FBcUMsNkJBQTZCO0FBQ2xFLGtDQUFpQyx3QkFBd0I7QUFDekQsbUNBQWtDO0FBQ2xDO0FBQ0EsVUFBUztBQUNUO0FBQ0E7QUFDQTtBQUNBLGtDQUFpQyw4QkFBOEI7QUFDL0Qsb0NBQW1DLGdDQUFnQztBQUNuRSxzQ0FBcUM7QUFDckMsWUFBVztBQUNYO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsVUFBUztBQUNUO0FBQ0E7QUFDQTtBQUNBLGtDQUFpQyw4QkFBOEI7QUFDL0Qsb0NBQW1DLGdDQUFnQztBQUNuRSxzQ0FBcUM7QUFDckMsWUFBVztBQUNYO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLE1BQUs7QUFDTDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsVUFBUztBQUNUO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxVQUFTO0FBQ1Q7QUFDQTtBQUNBO0FBQ0E7QUFDQSxZQUFXO0FBQ1g7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EscUNBQW9DLCtCQUErQjtBQUNuRTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxjQUFhO0FBQ2I7QUFDQTtBQUNBLHFDQUFvQyw4QkFBOEI7QUFDbEU7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLFVBQVM7QUFDVDtBQUNBO0FBQ0E7QUFDQTtBQUNBLFlBQVc7QUFDWDtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxxQ0FBb0MsK0JBQStCO0FBQ25FO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBLGNBQWE7QUFDYjtBQUNBO0FBQ0EscUNBQW9DLDhCQUE4QjtBQUNsRTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxFOzs7Ozs7O0FDL0tBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxJQUFHO0FBQ0g7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxJQUFHO0FBQ0g7QUFDQTtBQUNBO0FBQ0EsSUFBRztBQUNIO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0EsSUFBRztBQUNIO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxJQUFHO0FBQ0g7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQSxFOzs7Ozs7Ozs7QUNnQ0EscUJBQ0E7cUJBQ0E7WUFDQTtLQUNBO2tCQUNBO2VBQ0E7ZUFDQTtBQUNBO3FCQUNBOzs7O1dBSUE7WUFDQTtnQkFFQTtBQUpBO3VCQUtBO1dBQ0E7OzhCQUVBO2NBQ0E7YUFFQTtBQUpBOzs4QkFNQTtjQUNBO2FBRUE7QUFKQTs7OEJBTUE7cUJBQ0E7YUFFQTtBQUpBOzs4QkFNQTtxQkFDQTthQUlBO0FBTkE7QUF2QkE7OztxQ0ErQkE7bURBRUE7OzZEQUNBO2tDQUNBO0FBQ0E7QUFDQTtxQ0FDQTttREFDQTs2REFDQTtrQ0FDQTtBQUNBO0FBRUE7QUFkQTtBQS9CQTs7Ozs7Ozs7O0FDdkZBO0FBQ0E7QUFDQTs7QUFFQTs7QUFFQTtBQUNBO0FBQ0E7QUFDQTs7QUFFQTs7QUFFQTs7QUFFQSxFQUFDIiwiZmlsZSI6InBhZ2VzL2luZm8td2luZG93LmpzIiwic291cmNlc0NvbnRlbnQiOlsiIFx0Ly8gVGhlIG1vZHVsZSBjYWNoZVxuIFx0dmFyIGluc3RhbGxlZE1vZHVsZXMgPSB7fTtcblxuIFx0Ly8gVGhlIHJlcXVpcmUgZnVuY3Rpb25cbiBcdGZ1bmN0aW9uIF9fd2VicGFja19yZXF1aXJlX18obW9kdWxlSWQpIHtcblxuIFx0XHQvLyBDaGVjayBpZiBtb2R1bGUgaXMgaW4gY2FjaGVcbiBcdFx0aWYoaW5zdGFsbGVkTW9kdWxlc1ttb2R1bGVJZF0pXG4gXHRcdFx0cmV0dXJuIGluc3RhbGxlZE1vZHVsZXNbbW9kdWxlSWRdLmV4cG9ydHM7XG5cbiBcdFx0Ly8gQ3JlYXRlIGEgbmV3IG1vZHVsZSAoYW5kIHB1dCBpdCBpbnRvIHRoZSBjYWNoZSlcbiBcdFx0dmFyIG1vZHVsZSA9IGluc3RhbGxlZE1vZHVsZXNbbW9kdWxlSWRdID0ge1xuIFx0XHRcdGV4cG9ydHM6IHt9LFxuIFx0XHRcdGlkOiBtb2R1bGVJZCxcbiBcdFx0XHRsb2FkZWQ6IGZhbHNlXG4gXHRcdH07XG5cbiBcdFx0Ly8gRXhlY3V0ZSB0aGUgbW9kdWxlIGZ1bmN0aW9uXG4gXHRcdG1vZHVsZXNbbW9kdWxlSWRdLmNhbGwobW9kdWxlLmV4cG9ydHMsIG1vZHVsZSwgbW9kdWxlLmV4cG9ydHMsIF9fd2VicGFja19yZXF1aXJlX18pO1xuXG4gXHRcdC8vIEZsYWcgdGhlIG1vZHVsZSBhcyBsb2FkZWRcbiBcdFx0bW9kdWxlLmxvYWRlZCA9IHRydWU7XG5cbiBcdFx0Ly8gUmV0dXJuIHRoZSBleHBvcnRzIG9mIHRoZSBtb2R1bGVcbiBcdFx0cmV0dXJuIG1vZHVsZS5leHBvcnRzO1xuIFx0fVxuXG5cbiBcdC8vIGV4cG9zZSB0aGUgbW9kdWxlcyBvYmplY3QgKF9fd2VicGFja19tb2R1bGVzX18pXG4gXHRfX3dlYnBhY2tfcmVxdWlyZV9fLm0gPSBtb2R1bGVzO1xuXG4gXHQvLyBleHBvc2UgdGhlIG1vZHVsZSBjYWNoZVxuIFx0X193ZWJwYWNrX3JlcXVpcmVfXy5jID0gaW5zdGFsbGVkTW9kdWxlcztcblxuIFx0Ly8gX193ZWJwYWNrX3B1YmxpY19wYXRoX19cbiBcdF9fd2VicGFja19yZXF1aXJlX18ucCA9IFwiXCI7XG5cbiBcdC8vIExvYWQgZW50cnkgbW9kdWxlIGFuZCByZXR1cm4gZXhwb3J0c1xuIFx0cmV0dXJuIF9fd2VicGFja19yZXF1aXJlX18oMCk7XG5cblxuXG4vLyBXRUJQQUNLIEZPT1RFUiAvL1xuLy8gd2VicGFjay9ib290c3RyYXAgODBkODM0NjI0ODcxNjNhMWZkMTEiLCJyZXF1aXJlKFwiLi9pbmZvLXdpbmRvdy53ZVwiKVxudmFyIF9fd2VleF90ZW1wbGF0ZV9fID0gcmVxdWlyZShcIiEhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL2pzb24uanMhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL3RlbXBsYXRlLmpzIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP3R5cGU9dGVtcGxhdGUhLi9pbmZvLXdpbmRvdy53ZVwiKVxudmFyIF9fd2VleF9zdHlsZV9fID0gcmVxdWlyZShcIiEhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL2pzb24uanMhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL3N0eWxlLmpzIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP2luZGV4PTAmdHlwZT1zdHlsZXMhLi9pbmZvLXdpbmRvdy53ZVwiKVxudmFyIF9fd2VleF9zY3JpcHRfXyA9IHJlcXVpcmUoXCIhIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9zY3JpcHQuanMhYmFiZWwtbG9hZGVyP3ByZXNldHNbXT0vVXNlcnMvYWxpLTEzMDI1N24vd3d3L2FwcC9ub2RlX21vZHVsZXMvYmFiZWwtcHJlc2V0LWVzMjAxNSZwcmVzZXRzPS9Vc2Vycy9hbGktMTMwMjU3bi93d3cvYXBwL25vZGVfbW9kdWxlcy9iYWJlbC1wcmVzZXQtZXMyMDE1JnBsdWdpbnNbXT0vVXNlcnMvYWxpLTEzMDI1N24vd3d3L2FwcC9ub2RlX21vZHVsZXMvYmFiZWwtcGx1Z2luLXRyYW5zZm9ybS1ydW50aW1lJnBsdWdpbnM9L1VzZXJzL2FsaS0xMzAyNTduL3d3dy9hcHAvbm9kZV9tb2R1bGVzL2JhYmVsLXBsdWdpbi10cmFuc2Zvcm0tcnVudGltZSZjb21tZW50cz1mYWxzZSEuLy4uLy4uL25vZGVfbW9kdWxlcy93ZWV4LWxvYWRlci9saWIvZXh0cmFjdC5qcz9pbmRleD0wJnR5cGU9c2NyaXB0cyEuL2luZm8td2luZG93LndlXCIpXG5cbl9fd2VleF9kZWZpbmVfXygnQHdlZXgtY29tcG9uZW50LzFmNTg5MDBiNGNkZGY5YTc5MjNlNjlkYTk1NzZiM2Q4JywgW10sIGZ1bmN0aW9uKF9fd2VleF9yZXF1aXJlX18sIF9fd2VleF9leHBvcnRzX18sIF9fd2VleF9tb2R1bGVfXykge1xuXG4gICAgX193ZWV4X3NjcmlwdF9fKF9fd2VleF9tb2R1bGVfXywgX193ZWV4X2V4cG9ydHNfXywgX193ZWV4X3JlcXVpcmVfXylcbiAgICBpZiAoX193ZWV4X2V4cG9ydHNfXy5fX2VzTW9kdWxlICYmIF9fd2VleF9leHBvcnRzX18uZGVmYXVsdCkge1xuICAgICAgX193ZWV4X21vZHVsZV9fLmV4cG9ydHMgPSBfX3dlZXhfZXhwb3J0c19fLmRlZmF1bHRcbiAgICB9XG5cbiAgICBfX3dlZXhfbW9kdWxlX18uZXhwb3J0cy50ZW1wbGF0ZSA9IF9fd2VleF90ZW1wbGF0ZV9fXG5cbiAgICBfX3dlZXhfbW9kdWxlX18uZXhwb3J0cy5zdHlsZSA9IF9fd2VleF9zdHlsZV9fXG5cbn0pXG5cbl9fd2VleF9ib290c3RyYXBfXygnQHdlZXgtY29tcG9uZW50LzFmNTg5MDBiNGNkZGY5YTc5MjNlNjlkYTk1NzZiM2Q4Jyx1bmRlZmluZWQsdW5kZWZpbmVkKVxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vc3JjL3BhZ2VzL2luZm8td2luZG93LndlP2VudHJ5PXRydWVcbi8vIG1vZHVsZSBpZCA9IDBcbi8vIG1vZHVsZSBjaHVua3MgPSA5IiwibW9kdWxlLmV4cG9ydHMgPSB7XG4gIFwidHlwZVwiOiBcImRpdlwiLFxuICBcImNsYXNzTGlzdFwiOiBbXG4gICAgXCJpbmZvLXdpblwiXG4gIF0sXG4gIFwiY2hpbGRyZW5cIjogW1xuICAgIHtcbiAgICAgIFwidHlwZVwiOiBcImltYWdlXCIsXG4gICAgICBcImNsYXNzTGlzdFwiOiBbXG4gICAgICAgIFwiY292ZXJcIlxuICAgICAgXSxcbiAgICAgIFwiYXR0clwiOiB7XG4gICAgICAgIFwic3JjXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5zcmN9XG4gICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICBcInR5cGVcIjogXCJ0ZXh0XCIsXG4gICAgICBcImNsYXNzTGlzdFwiOiBbXG4gICAgICAgIFwiZGVzY1wiXG4gICAgICBdLFxuICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgXCJ2YWx1ZVwiOiBmdW5jdGlvbiAoKSB7cmV0dXJuIHRoaXMudGl0bGV9XG4gICAgICB9XG4gICAgfSxcbiAgICB7XG4gICAgICBcInR5cGVcIjogXCJ0ZXh0XCIsXG4gICAgICBcImNsYXNzTGlzdFwiOiBbXG4gICAgICAgIFwiYWRkcmVzc1wiXG4gICAgICBdLFxuICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgXCJ2YWx1ZVwiOiBmdW5jdGlvbiAoKSB7cmV0dXJuIHRoaXMubG9jYXRpb259XG4gICAgICB9XG4gICAgfVxuICBdXG59XG5cblxuLy8vLy8vLy8vLy8vLy8vLy8vXG4vLyBXRUJQQUNLIEZPT1RFUlxuLy8gLi9+L3dlZXgtbG9hZGVyL2xpYi9qc29uLmpzIS4vfi93ZWV4LWxvYWRlci9saWIvdGVtcGxhdGUuanMhLi9+L3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP3R5cGU9dGVtcGxhdGUhLi9zcmMvaW5jbHVkZS9pbmZvLXdpbmRvdy53ZVxuLy8gbW9kdWxlIGlkID0gOTBcbi8vIG1vZHVsZSBjaHVua3MgPSAyIDkiLCJtb2R1bGUuZXhwb3J0cyA9IHtcbiAgXCJpbmZvLXdpblwiOiB7XG4gICAgXCJ3aWR0aFwiOiA1MDAsXG4gICAgXCJwYWRkaW5nXCI6IDUsXG4gICAgXCJiYWNrZ3JvdW5kQ29sb3JcIjogXCIjZmZmZmZmXCIsXG4gICAgXCJib3JkZXJXaWR0aFwiOiAxLFxuICAgIFwiYm9yZGVyQ29sb3JcIjogXCJyZ2JhKDAsMCwwLDAuMSlcIixcbiAgICBcImJvcmRlckJvdHRvbVdpZHRoXCI6IDIsXG4gICAgXCJib3JkZXJCb3R0b21Db2xvclwiOiBcInJnYmEoMCwwLDAsMC4yNSlcIlxuICB9LFxuICBcImNvdmVyXCI6IHtcbiAgICBcImZsZXhcIjogMSxcbiAgICBcImhlaWdodFwiOiAxODBcbiAgfSxcbiAgXCJkZXNjXCI6IHtcbiAgICBcImZvbnRTaXplXCI6IDIwLFxuICAgIFwiYmFja2dyb3VuZENvbG9yXCI6IFwiI2ZmZmZmZlwiLFxuICAgIFwicGFkZGluZ1wiOiA1XG4gIH0sXG4gIFwiYWRkcmVzc1wiOiB7XG4gICAgXCJmb250U2l6ZVwiOiAxNixcbiAgICBcImNvbG9yXCI6IFwiIzk5OTk5OVwiLFxuICAgIFwiYmFja2dyb3VuZENvbG9yXCI6IFwiI2ZmZmZmZlwiLFxuICAgIFwicGFkZGluZ1wiOiA1LFxuICAgIFwicGFkZGluZ0JvdHRvbVwiOiAxMFxuICB9XG59XG5cblxuLy8vLy8vLy8vLy8vLy8vLy8vXG4vLyBXRUJQQUNLIEZPT1RFUlxuLy8gLi9+L3dlZXgtbG9hZGVyL2xpYi9qc29uLmpzIS4vfi93ZWV4LWxvYWRlci9saWIvc3R5bGUuanMhLi9+L3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP2luZGV4PTAmdHlwZT1zdHlsZXMhLi9zcmMvaW5jbHVkZS9pbmZvLXdpbmRvdy53ZVxuLy8gbW9kdWxlIGlkID0gOTFcbi8vIG1vZHVsZSBjaHVua3MgPSAyIDkiLCI8dGVtcGxhdGU+XG48ZGl2IGNsYXNzPVwiaW5mby13aW5cIj5cbiAgPGltYWdlIGNsYXNzPVwiY292ZXJcIiBzcmM9XCJ7e3NyY319XCIvPlxuICA8dGV4dCBjbGFzcz1cImRlc2NcIj57e3RpdGxlfX08L3RleHQ+XG4gIDx0ZXh0IGNsYXNzPVwiYWRkcmVzc1wiPnt7bG9jYXRpb259fTwvdGV4dD5cbjwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuaW5mby13aW57XG4gICAgd2lkdGg6IDUwMDtcbiAgICBwYWRkaW5nOiA1O1xuICAgIGJhY2tncm91bmQtY29sb3I6ICNmZmY7XG4gICAgYm9yZGVyLXdpZHRoOiAxO1xuICAgIGJvcmRlci1jb2xvcjogcmdiYSgwLDAsMCwuMSk7XG4gICAgYm9yZGVyLWJvdHRvbS13aWR0aDogMjtcbiAgICBib3JkZXItYm90dG9tLWNvbG9yOiByZ2JhKDAsMCwwLC4yNSk7XG4gIH1cbiAgLmNvdmVye1xuICAgIGZsZXg6IDE7XG4gICAgaGVpZ2h0OiAxODA7XG4gIH1cbiAgLmRlc2N7XG4gICAgZm9udC1zaXplOiAyMDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmO1xuICAgIHBhZGRpbmc6IDU7XG4gIH1cbiAgLmFkZHJlc3N7XG4gICAgZm9udC1zaXplOiAxNjtcbiAgICBjb2xvcjogIzk5OTtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmO1xuICAgIHBhZGRpbmc6IDU7XG4gICAgcGFkZGluZy1ib3R0b206IDEwO1xuICB9XG48L3N0eWxlPlxuXG48c2NyaXB0PlxuICBleHBvcnQgZGVmYXVsdCB7XG4gICAgXG4gIH07XG48L3NjcmlwdD5cblxuXG4vLyBXRUJQQUNLIEZPT1RFUiAvL1xuLy8gLi9zcmMvaW5jbHVkZS9pbmZvLXdpbmRvdy53ZT85ODFmZjcwYSIsIm1vZHVsZS5leHBvcnRzID0ge1xuICBcInR5cGVcIjogXCJkaXZcIixcbiAgXCJjbGFzc0xpc3RcIjogW1xuICAgIFwibmF2YmFyLWNvblwiXG4gIF0sXG4gIFwiY2hpbGRyZW5cIjogW1xuICAgIHtcbiAgICAgIFwidHlwZVwiOiBcImRpdlwiLFxuICAgICAgXCJjbGFzc0xpc3RcIjogW1xuICAgICAgICBcIm5hdmJhclwiXG4gICAgICBdLFxuICAgICAgXCJjaGlsZHJlblwiOiBbXG4gICAgICAgIHtcbiAgICAgICAgICBcInR5cGVcIjogXCJkaXZcIixcbiAgICAgICAgICBcImNsYXNzTGlzdFwiOiBbXG4gICAgICAgICAgICBcImJ0bi1iYWNrXCJcbiAgICAgICAgICBdLFxuICAgICAgICAgIFwiZXZlbnRzXCI6IHtcbiAgICAgICAgICAgIFwiY2xpY2tcIjogXCJnb0hvbWVcIlxuICAgICAgICAgIH0sXG4gICAgICAgICAgXCJjaGlsZHJlblwiOiBbXG4gICAgICAgICAgICB7XG4gICAgICAgICAgICAgIFwidHlwZVwiOiBcImltYWdlXCIsXG4gICAgICAgICAgICAgIFwiY2xhc3NMaXN0XCI6IFtcbiAgICAgICAgICAgICAgICBcImJ0bi1hcnJvdy1sZWZ0XCJcbiAgICAgICAgICAgICAgXSxcbiAgICAgICAgICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgICAgICAgICBcInNyY1wiOiBcImh0dHA6Ly9pbWcxLnZ1ZWQudmFudGhpbmsuY24vdnVlZDljOGU3ZTczOGZmOTRhYmVlMjNlYjY5ZDdmMTQwMWU5LnBuZ1wiXG4gICAgICAgICAgICAgIH1cbiAgICAgICAgICAgIH0sXG4gICAgICAgICAgICB7XG4gICAgICAgICAgICAgIFwidHlwZVwiOiBcInRleHRcIixcbiAgICAgICAgICAgICAgXCJjbGFzc0xpc3RcIjogW1xuICAgICAgICAgICAgICAgIFwiYnRuLXRleHRcIlxuICAgICAgICAgICAgICBdLFxuICAgICAgICAgICAgICBcImF0dHJcIjoge1xuICAgICAgICAgICAgICAgIFwidmFsdWVcIjogXCLov5Tlm55cIlxuICAgICAgICAgICAgICB9XG4gICAgICAgICAgICB9XG4gICAgICAgICAgXVxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgXCJ0eXBlXCI6IFwidGV4dFwiLFxuICAgICAgICAgIFwiY2xhc3NMaXN0XCI6IFtcbiAgICAgICAgICAgIFwidGl0bGVcIlxuICAgICAgICAgIF0sXG4gICAgICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgICAgIFwidmFsdWVcIjogZnVuY3Rpb24gKCkge3JldHVybiB0aGlzLnRpdGxlfVxuICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgXVxuICAgIH1cbiAgXVxufVxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vfi93ZWV4LWxvYWRlci9saWIvanNvbi5qcyEuL34vd2VleC1sb2FkZXIvbGliL3RlbXBsYXRlLmpzIS4vfi93ZWV4LWxvYWRlci9saWIvZXh0cmFjdC5qcz90eXBlPXRlbXBsYXRlIS4vc3JjL2luY2x1ZGUvbmF2YmFyLndlXG4vLyBtb2R1bGUgaWQgPSA5M1xuLy8gbW9kdWxlIGNodW5rcyA9IDMgNSA2IDcgOCA5IDEwIDExIDEyIDEzIDE0IDE1IDE2IDE3IiwibW9kdWxlLmV4cG9ydHMgPSB7XG4gIFwibmF2YmFyLWNvblwiOiB7XG4gICAgXCJoZWlnaHRcIjogOTgsXG4gICAgXCJwYWRkaW5nVG9wXCI6IDEwXG4gIH0sXG4gIFwibmF2YmFyXCI6IHtcbiAgICBcInpJbmRleFwiOiAxMDAwLFxuICAgIFwicG9zaXRpb25cIjogXCJyZWxhdGl2ZVwiLFxuICAgIFwiZGlzcGxheVwiOiBcImZsZXhcIixcbiAgICBcImZsZXhEaXJlY3Rpb25cIjogXCJyb3dcIixcbiAgICBcImhlaWdodFwiOiA4OCxcbiAgICBcImJhY2tncm91bmRDb2xvclwiOiBcIiNmZmZmZmZcIixcbiAgICBcImFsaWduSXRlbXNcIjogXCJjZW50ZXJcIixcbiAgICBcImJvcmRlckJvdHRvbVdpZHRoXCI6IDIsXG4gICAgXCJib3JkZXJCb3R0b21Db2xvclwiOiBcIiNkZGRkZGRcIlxuICB9LFxuICBcImJ0bi1iYWNrXCI6IHtcbiAgICBcInpJbmRleFwiOiAxMDAyLFxuICAgIFwiZmxleERpcmVjdGlvblwiOiBcInJvd1wiLFxuICAgIFwiYWxpZ25JdGVtc1wiOiBcImNlbnRlclwiLFxuICAgIFwid2lkdGhcIjogMTgwLFxuICAgIFwiaGVpZ2h0XCI6IDg4XG4gIH0sXG4gIFwiYnRuLWFycm93LWxlZnRcIjoge1xuICAgIFwid2lkdGhcIjogNjAsXG4gICAgXCJoZWlnaHRcIjogNjAsXG4gICAgXCJtYXJnaW5MZWZ0XCI6IDEwXG4gIH0sXG4gIFwiYnRuLXRleHRcIjoge1xuICAgIFwiY29sb3JcIjogXCIjMGY4OWY1XCJcbiAgfSxcbiAgXCJ0aXRsZVwiOiB7XG4gICAgXCJwb3NpdGlvblwiOiBcImFic29sdXRlXCIsXG4gICAgXCJsZWZ0XCI6IDE4MCxcbiAgICBcInJpZ2h0XCI6IDE4MCxcbiAgICBcInRvcFwiOiAwLFxuICAgIFwiaGVpZ2h0XCI6IDg4LFxuICAgIFwibGluZUhlaWdodFwiOiA4OCxcbiAgICBcImZvbnRTaXplXCI6IDM2LFxuICAgIFwidGV4dEFsaWduXCI6IFwiY2VudGVyXCJcbiAgfVxufVxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vfi93ZWV4LWxvYWRlci9saWIvanNvbi5qcyEuL34vd2VleC1sb2FkZXIvbGliL3N0eWxlLmpzIS4vfi93ZWV4LWxvYWRlci9saWIvZXh0cmFjdC5qcz9pbmRleD0wJnR5cGU9c3R5bGVzIS4vc3JjL2luY2x1ZGUvbmF2YmFyLndlXG4vLyBtb2R1bGUgaWQgPSA5NFxuLy8gbW9kdWxlIGNodW5rcyA9IDMgNSA2IDcgOCA5IDEwIDExIDEyIDEzIDE0IDE1IDE2IDE3IiwiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibmF2YmFyLWNvblwiPlxuICAgIDxkaXYgY2xhc3M9XCJuYXZiYXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJidG4tYmFja1wiIG9uY2xpY2s9XCJnb0hvbWVcIj5cbiAgICAgICAgPGltYWdlIGNsYXNzPVwiYnRuLWFycm93LWxlZnRcIiBzcmM9XCJodHRwOi8vaW1nMS52dWVkLnZhbnRoaW5rLmNuL3Z1ZWQ5YzhlN2U3MzhmZjk0YWJlZTIzZWI2OWQ3ZjE0MDFlOS5wbmdcIj48L2ltYWdlPlxuICAgICAgICA8dGV4dCBjbGFzcz1cImJ0bi10ZXh0XCI+6L+U5ZuePC90ZXh0PlxuICAgICAgPC9kaXY+XG4gICAgICA8dGV4dCBjbGFzcz1cInRpdGxlXCI+e3t0aXRsZX19PC90ZXh0PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG48c3R5bGU+XG4gIC5uYXZiYXItY29ue1xuICAgIGhlaWdodDogOTg7XG4gICAgcGFkZGluZy10b3A6IDEwO1xuICB9XG4gIC5uYXZiYXJ7XG4gICAgei1pbmRleDogMTAwMDtcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gICAgZGlzcGxheTpmbGV4O1xuICAgIGZsZXgtZGlyZWN0aW9uOiByb3c7XG4gICAgaGVpZ2h0OiA4ODtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZmZmO1xuICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gICAgYm9yZGVyLWJvdHRvbS13aWR0aDogMjtcbiAgICBib3JkZXItYm90dG9tLWNvbG9yOiAjZGRkO1xuICB9XG4gIC5idG4tYmFja3tcbiAgICB6LWluZGV4OiAxMDAyO1xuICAgIGZsZXgtZGlyZWN0aW9uOiByb3c7XG4gICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAgICB3aWR0aDogMTgwO1xuICAgIGhlaWdodDogODg7XG4gIH1cbiAgLmJ0bi1hcnJvdy1sZWZ0e1xuICAgIHdpZHRoOiA2MDtcbiAgICBoZWlnaHQ6IDYwO1xuICAgIG1hcmdpbi1sZWZ0OiAxMDtcbiAgfVxuICAuYnRuLXRleHR7XG4gICAgY29sb3I6ICMwZjg5ZjU7XG4gIH1cbiAgLnRpdGxle1xuICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICBsZWZ0OjE4MDtcbiAgICByaWdodDoxODA7XG4gICAgdG9wOjA7XG4gICAgaGVpZ2h0OiA4ODtcbiAgICBsaW5lLWhlaWdodDogODg7XG4gICAgZm9udC1zaXplOiAzNjtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIH1cbjwvc3R5bGU+XG48c2NyaXB0PlxuICBjb25zdCBuYXZpZ2F0b3IgPSByZXF1aXJlKCdAd2VleC1tb2R1bGUvbmF2aWdhdG9yJyk7XG4gIG1vZHVsZS5leHBvcnRzID0ge1xuICAgIG1ldGhvZHM6IHtcbiAgICAgIGdvSG9tZSgpIHtcbiAgICAgICAgbmF2aWdhdG9yLnBvcCgpO1xuICAgICAgfVxuICAgIH0gICBcbiAgfVxuPC9zY3JpcHQ+XG5cblxuLy8gV0VCUEFDSyBGT09URVIgLy9cbi8vIC4vc3JjL2luY2x1ZGUvbmF2YmFyLndlPzE2NTJiYWE4IiwidmFyIF9fd2VleF90ZW1wbGF0ZV9fID0gcmVxdWlyZShcIiEhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL2pzb24uanMhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL3RlbXBsYXRlLmpzIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP3R5cGU9dGVtcGxhdGUhLi9uYXZiYXIud2VcIilcbnZhciBfX3dlZXhfc3R5bGVfXyA9IHJlcXVpcmUoXCIhIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9qc29uLmpzIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9zdHlsZS5qcyEuLy4uLy4uL25vZGVfbW9kdWxlcy93ZWV4LWxvYWRlci9saWIvZXh0cmFjdC5qcz9pbmRleD0wJnR5cGU9c3R5bGVzIS4vbmF2YmFyLndlXCIpXG52YXIgX193ZWV4X3NjcmlwdF9fID0gcmVxdWlyZShcIiEhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL3NjcmlwdC5qcyFiYWJlbC1sb2FkZXI/cHJlc2V0c1tdPS9Vc2Vycy9hbGktMTMwMjU3bi93d3cvYXBwL25vZGVfbW9kdWxlcy9iYWJlbC1wcmVzZXQtZXMyMDE1JnByZXNldHM9L1VzZXJzL2FsaS0xMzAyNTduL3d3dy9hcHAvbm9kZV9tb2R1bGVzL2JhYmVsLXByZXNldC1lczIwMTUmcGx1Z2luc1tdPS9Vc2Vycy9hbGktMTMwMjU3bi93d3cvYXBwL25vZGVfbW9kdWxlcy9iYWJlbC1wbHVnaW4tdHJhbnNmb3JtLXJ1bnRpbWUmcGx1Z2lucz0vVXNlcnMvYWxpLTEzMDI1N24vd3d3L2FwcC9ub2RlX21vZHVsZXMvYmFiZWwtcGx1Z2luLXRyYW5zZm9ybS1ydW50aW1lJmNvbW1lbnRzPWZhbHNlIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP2luZGV4PTAmdHlwZT1zY3JpcHRzIS4vbmF2YmFyLndlXCIpXG5cbl9fd2VleF9kZWZpbmVfXygnQHdlZXgtY29tcG9uZW50L25hdmJhcicsIFtdLCBmdW5jdGlvbihfX3dlZXhfcmVxdWlyZV9fLCBfX3dlZXhfZXhwb3J0c19fLCBfX3dlZXhfbW9kdWxlX18pIHtcblxuICAgIF9fd2VleF9zY3JpcHRfXyhfX3dlZXhfbW9kdWxlX18sIF9fd2VleF9leHBvcnRzX18sIF9fd2VleF9yZXF1aXJlX18pXG4gICAgaWYgKF9fd2VleF9leHBvcnRzX18uX19lc01vZHVsZSAmJiBfX3dlZXhfZXhwb3J0c19fLmRlZmF1bHQpIHtcbiAgICAgIF9fd2VleF9tb2R1bGVfXy5leHBvcnRzID0gX193ZWV4X2V4cG9ydHNfXy5kZWZhdWx0XG4gICAgfVxuXG4gICAgX193ZWV4X21vZHVsZV9fLmV4cG9ydHMudGVtcGxhdGUgPSBfX3dlZXhfdGVtcGxhdGVfX1xuXG4gICAgX193ZWV4X21vZHVsZV9fLmV4cG9ydHMuc3R5bGUgPSBfX3dlZXhfc3R5bGVfX1xuXG59KVxuXG5cblxuLy8vLy8vLy8vLy8vLy8vLy8vXG4vLyBXRUJQQUNLIEZPT1RFUlxuLy8gLi9zcmMvaW5jbHVkZS9uYXZiYXIud2Vcbi8vIG1vZHVsZSBpZCA9IDEwM1xuLy8gbW9kdWxlIGNodW5rcyA9IDUgNiA3IDggOSAxMCAxMSAxMiAxMyAxNCAxNSAxNiAxNyIsInJlcXVpcmUoXCIuL2luZm8td2luZG93LndlXCIpXG52YXIgX193ZWV4X3RlbXBsYXRlX18gPSByZXF1aXJlKFwiISEuLy4uLy4uL25vZGVfbW9kdWxlcy93ZWV4LWxvYWRlci9saWIvanNvbi5qcyEuLy4uLy4uL25vZGVfbW9kdWxlcy93ZWV4LWxvYWRlci9saWIvdGVtcGxhdGUuanMhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL2V4dHJhY3QuanM/dHlwZT10ZW1wbGF0ZSEuL2luZm8td2luZG93LndlXCIpXG52YXIgX193ZWV4X3N0eWxlX18gPSByZXF1aXJlKFwiISEuLy4uLy4uL25vZGVfbW9kdWxlcy93ZWV4LWxvYWRlci9saWIvanNvbi5qcyEuLy4uLy4uL25vZGVfbW9kdWxlcy93ZWV4LWxvYWRlci9saWIvc3R5bGUuanMhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL2V4dHJhY3QuanM/aW5kZXg9MCZ0eXBlPXN0eWxlcyEuL2luZm8td2luZG93LndlXCIpXG52YXIgX193ZWV4X3NjcmlwdF9fID0gcmVxdWlyZShcIiEhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL3NjcmlwdC5qcyFiYWJlbC1sb2FkZXI/cHJlc2V0c1tdPS9Vc2Vycy9hbGktMTMwMjU3bi93d3cvYXBwL25vZGVfbW9kdWxlcy9iYWJlbC1wcmVzZXQtZXMyMDE1JnByZXNldHM9L1VzZXJzL2FsaS0xMzAyNTduL3d3dy9hcHAvbm9kZV9tb2R1bGVzL2JhYmVsLXByZXNldC1lczIwMTUmcGx1Z2luc1tdPS9Vc2Vycy9hbGktMTMwMjU3bi93d3cvYXBwL25vZGVfbW9kdWxlcy9iYWJlbC1wbHVnaW4tdHJhbnNmb3JtLXJ1bnRpbWUmcGx1Z2lucz0vVXNlcnMvYWxpLTEzMDI1N24vd3d3L2FwcC9ub2RlX21vZHVsZXMvYmFiZWwtcGx1Z2luLXRyYW5zZm9ybS1ydW50aW1lJmNvbW1lbnRzPWZhbHNlIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP2luZGV4PTAmdHlwZT1zY3JpcHRzIS4vaW5mby13aW5kb3cud2VcIilcblxuX193ZWV4X2RlZmluZV9fKCdAd2VleC1jb21wb25lbnQvaW5mby13aW5kb3cnLCBbXSwgZnVuY3Rpb24oX193ZWV4X3JlcXVpcmVfXywgX193ZWV4X2V4cG9ydHNfXywgX193ZWV4X21vZHVsZV9fKSB7XG5cbiAgICBfX3dlZXhfc2NyaXB0X18oX193ZWV4X21vZHVsZV9fLCBfX3dlZXhfZXhwb3J0c19fLCBfX3dlZXhfcmVxdWlyZV9fKVxuICAgIGlmIChfX3dlZXhfZXhwb3J0c19fLl9fZXNNb2R1bGUgJiYgX193ZWV4X2V4cG9ydHNfXy5kZWZhdWx0KSB7XG4gICAgICBfX3dlZXhfbW9kdWxlX18uZXhwb3J0cyA9IF9fd2VleF9leHBvcnRzX18uZGVmYXVsdFxuICAgIH1cblxuICAgIF9fd2VleF9tb2R1bGVfXy5leHBvcnRzLnRlbXBsYXRlID0gX193ZWV4X3RlbXBsYXRlX19cblxuICAgIF9fd2VleF9tb2R1bGVfXy5leHBvcnRzLnN0eWxlID0gX193ZWV4X3N0eWxlX19cblxufSlcblxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vc3JjL3BhZ2VzL2luZm8td2luZG93LndlXG4vLyBtb2R1bGUgaWQgPSAxMTNcbi8vIG1vZHVsZSBjaHVua3MgPSA5IiwibW9kdWxlLmV4cG9ydHMgPSB7XG4gIFwidHlwZVwiOiBcImRpdlwiLFxuICBcImNsYXNzTGlzdFwiOiBbXG4gICAgXCJjb250YWluZXJcIlxuICBdLFxuICBcImNoaWxkcmVuXCI6IFtcbiAgICB7XG4gICAgICBcInR5cGVcIjogXCJuYXZiYXJcIixcbiAgICAgIFwiYXR0clwiOiB7XG4gICAgICAgIFwidGl0bGVcIjogXCLorr7nva7oh6rlrprkuYnkv6Hmga/nqpfkvZNcIlxuICAgICAgfVxuICAgIH0sXG4gICAge1xuICAgICAgXCJ0eXBlXCI6IFwid2VleC1hbWFwXCIsXG4gICAgICBcImNsYXNzTGlzdFwiOiBbXG4gICAgICAgIFwibWFwXCJcbiAgICAgIF0sXG4gICAgICBcImlkXCI6IFwibWFwMjAxN1wiLFxuICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgXCJzZGtLZXlcIjogZnVuY3Rpb24gKCkge3JldHVybiB0aGlzLmtleXN9LFxuICAgICAgICBcInpvb21cIjogZnVuY3Rpb24gKCkge3JldHVybiB0aGlzLnpvb219LFxuICAgICAgICBcImNlbnRlclwiOiBmdW5jdGlvbiAoKSB7cmV0dXJuIHRoaXMucG9zfVxuICAgICAgfSxcbiAgICAgIFwiY2hpbGRyZW5cIjogW1xuICAgICAgICB7XG4gICAgICAgICAgXCJ0eXBlXCI6IFwid2VleC1hbWFwLW1hcmtlclwiLFxuICAgICAgICAgIFwic3R5bGVcIjoge1xuICAgICAgICAgICAgXCJ6SW5kZXhcIjogMTAwMFxuICAgICAgICAgIH0sXG4gICAgICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgICAgIFwiaGlkZUNhbGxvdXRcIjogXCJ0cnVlXCIsXG4gICAgICAgICAgICBcInBvc2l0aW9uXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5tYXJrZXIucG9zaXRpb259LFxuICAgICAgICAgICAgXCJpY29uXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5tYXJrZXIuaWNvbn0sXG4gICAgICAgICAgICBcInRpdGxlXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5tYXJrZXIudGl0bGV9XG4gICAgICAgICAgfVxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgXCJ0eXBlXCI6IFwid2VleC1hbWFwLW1hcmtlclwiLFxuICAgICAgICAgIFwic3R5bGVcIjoge1xuICAgICAgICAgICAgXCJ6SW5kZXhcIjogMTAwMFxuICAgICAgICAgIH0sXG4gICAgICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgICAgIFwiaGlkZUNhbGxvdXRcIjogXCJ0cnVlXCIsXG4gICAgICAgICAgICBcInBvc2l0aW9uXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5tYXJrZXIyLnBvc2l0aW9ufSxcbiAgICAgICAgICAgIFwiaWNvblwiOiBmdW5jdGlvbiAoKSB7cmV0dXJuIHRoaXMubWFya2VyLmljb259LFxuICAgICAgICAgICAgXCJ0aXRsZVwiOiBmdW5jdGlvbiAoKSB7cmV0dXJuIHRoaXMubWFya2VyMi50aXRsZX1cbiAgICAgICAgICB9XG4gICAgICAgIH0sXG4gICAgICAgIHtcbiAgICAgICAgICBcInR5cGVcIjogXCJ3ZWV4LWFtYXAtaW5mby13aW5kb3dcIixcbiAgICAgICAgICBcImF0dHJcIjoge1xuICAgICAgICAgICAgXCJvcGVuXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5wYWxhY2VNdXNldW0ub3Blbn0sXG4gICAgICAgICAgICBcIm9mZnNldFwiOiBmdW5jdGlvbiAoKSB7cmV0dXJuIHRoaXMucGFsYWNlTXVzZXVtLm9mZnNldH0sXG4gICAgICAgICAgICBcInBvc2l0aW9uXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5wYWxhY2VNdXNldW0ucG9zaXRpb259XG4gICAgICAgICAgfSxcbiAgICAgICAgICBcImNoaWxkcmVuXCI6IFtcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgXCJ0eXBlXCI6IFwiaW5mby13aW5kb3dcIixcbiAgICAgICAgICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgICAgICAgICBcInNyY1wiOiBcImh0dHA6Ly9pbWcxLnZ1ZWQudmFudGhpbmsuY24vdnVlZDZkZmQ5OThmYzA3MzhmN2U4OGQ0YjY2YmFmYzU0N2NlLmpwZWdcIixcbiAgICAgICAgICAgICAgICBcInRpdGxlXCI6IFwiVGhlIFBhbGFjZSBNdXNldW1cIixcbiAgICAgICAgICAgICAgICBcImxvY2F0aW9uXCI6IFwiNCBKaW5nc2hhbiBGcm9udCBTdCwgRG9uZ2NoZW5nIFF1LCBCZWlqaW5nXCJcbiAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgfVxuICAgICAgICAgIF1cbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIFwidHlwZVwiOiBcIndlZXgtYW1hcC1pbmZvLXdpbmRvd1wiLFxuICAgICAgICAgIFwiYXR0clwiOiB7XG4gICAgICAgICAgICBcIm9wZW5cIjogZnVuY3Rpb24gKCkge3JldHVybiB0aGlzLnNvdXRoU3RhdGlvbi5vcGVufSxcbiAgICAgICAgICAgIFwib2Zmc2V0XCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5zb3V0aFN0YXRpb24ub2Zmc2V0fSxcbiAgICAgICAgICAgIFwicG9zaXRpb25cIjogZnVuY3Rpb24gKCkge3JldHVybiB0aGlzLnNvdXRoU3RhdGlvbi5wb3NpdGlvbn1cbiAgICAgICAgICB9LFxuICAgICAgICAgIFwiY2hpbGRyZW5cIjogW1xuICAgICAgICAgICAge1xuICAgICAgICAgICAgICBcInR5cGVcIjogXCJpbmZvLXdpbmRvd1wiLFxuICAgICAgICAgICAgICBcImF0dHJcIjoge1xuICAgICAgICAgICAgICAgIFwic3JjXCI6IFwiaHR0cDovL2ltZzEudnVlZC52YW50aGluay5jbi92dWVkMmRlMzAyZWY3MmFlOTIxMzEzYTFmYTFiYmJiZDk0NTUuanBlZ1wiLFxuICAgICAgICAgICAgICAgIFwidGl0bGVcIjogXCJCZWlqaW5nIFNvdXRoIFJhaWx3YXkgU3RhdGlvblwiLFxuICAgICAgICAgICAgICAgIFwibG9jYXRpb25cIjogXCJGZW5ndGFpLCBCZWlqaW5nXCJcbiAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgfVxuICAgICAgICAgIF1cbiAgICAgICAgfVxuICAgICAgXVxuICAgIH0sXG4gICAge1xuICAgICAgXCJ0eXBlXCI6IFwiZGl2XCIsXG4gICAgICBcImNsYXNzTGlzdFwiOiBbXG4gICAgICAgIFwibWFwLWNvbnRyb2xcIlxuICAgICAgXSxcbiAgICAgIFwiY2hpbGRyZW5cIjogW1xuICAgICAgICB7XG4gICAgICAgICAgXCJ0eXBlXCI6IFwidGV4dFwiLFxuICAgICAgICAgIFwiY2xhc3NMaXN0XCI6IFtcbiAgICAgICAgICAgIFwidGl0bGVcIlxuICAgICAgICAgIF0sXG4gICAgICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgICAgIFwidmFsdWVcIjogXCJDb21wb25lbnQ6IHdlZXgtYW1hcC1pbmZvLXdpbmRvd1wiXG4gICAgICAgICAgfVxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgXCJ0eXBlXCI6IFwidGV4dFwiLFxuICAgICAgICAgIFwiY2xhc3NMaXN0XCI6IFtcbiAgICAgICAgICAgIFwidGlwc1wiXG4gICAgICAgICAgXSxcbiAgICAgICAgICBcImF0dHJcIjoge1xuICAgICAgICAgICAgXCJ2YWx1ZVwiOiBcIuWcqOWcsOWbvuS4iuaYvuekuuiHquWumuS5ieeql+S9k1wiXG4gICAgICAgICAgfVxuICAgICAgICB9LFxuICAgICAgICB7XG4gICAgICAgICAgXCJ0eXBlXCI6IFwiZGl2XCIsXG4gICAgICAgICAgXCJldmVudHNcIjoge1xuICAgICAgICAgICAgXCJjbGlja1wiOiBcInRvZ2dsZU11c1wiXG4gICAgICAgICAgfSxcbiAgICAgICAgICBcImNsYXNzTGlzdFwiOiBbXG4gICAgICAgICAgICBcImJ0bmJveFwiXG4gICAgICAgICAgXSxcbiAgICAgICAgICBcImNoaWxkcmVuXCI6IFtcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgXCJ0eXBlXCI6IFwidGV4dFwiLFxuICAgICAgICAgICAgICBcInNob3duXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gIXRoaXMucGFsYWNlTXVzZXVtLm9wZW59LFxuICAgICAgICAgICAgICBcImNsYXNzTGlzdFwiOiBbXG4gICAgICAgICAgICAgICAgXCJidG5cIlxuICAgICAgICAgICAgICBdLFxuICAgICAgICAgICAgICBcImF0dHJcIjoge1xuICAgICAgICAgICAgICAgIFwidmFsdWVcIjogXCLmiZPlvIDmlYXlrqvkv6Hmga9cIlxuICAgICAgICAgICAgICB9XG4gICAgICAgICAgICB9LFxuICAgICAgICAgICAge1xuICAgICAgICAgICAgICBcInR5cGVcIjogXCJ0ZXh0XCIsXG4gICAgICAgICAgICAgIFwic2hvd25cIjogZnVuY3Rpb24gKCkge3JldHVybiB0aGlzLnBhbGFjZU11c2V1bS5vcGVufSxcbiAgICAgICAgICAgICAgXCJjbGFzc0xpc3RcIjogW1xuICAgICAgICAgICAgICAgIFwiYnRuXCJcbiAgICAgICAgICAgICAgXSxcbiAgICAgICAgICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgICAgICAgICBcInZhbHVlXCI6IFwi5YWz6Zet5pWF5a6r5L+h5oGvXCJcbiAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgfVxuICAgICAgICAgIF1cbiAgICAgICAgfSxcbiAgICAgICAge1xuICAgICAgICAgIFwidHlwZVwiOiBcImRpdlwiLFxuICAgICAgICAgIFwiZXZlbnRzXCI6IHtcbiAgICAgICAgICAgIFwiY2xpY2tcIjogXCJ0b2dnbGVTdGFcIlxuICAgICAgICAgIH0sXG4gICAgICAgICAgXCJjbGFzc0xpc3RcIjogW1xuICAgICAgICAgICAgXCJidG5ib3hcIlxuICAgICAgICAgIF0sXG4gICAgICAgICAgXCJjaGlsZHJlblwiOiBbXG4gICAgICAgICAgICB7XG4gICAgICAgICAgICAgIFwidHlwZVwiOiBcInRleHRcIixcbiAgICAgICAgICAgICAgXCJzaG93blwiOiBmdW5jdGlvbiAoKSB7cmV0dXJuICF0aGlzLnNvdXRoU3RhdGlvbi5vcGVufSxcbiAgICAgICAgICAgICAgXCJjbGFzc0xpc3RcIjogW1xuICAgICAgICAgICAgICAgIFwiYnRuXCJcbiAgICAgICAgICAgICAgXSxcbiAgICAgICAgICAgICAgXCJhdHRyXCI6IHtcbiAgICAgICAgICAgICAgICBcInZhbHVlXCI6IFwi5omT5byA5Y2X56uZ5L+h5oGvXCJcbiAgICAgICAgICAgICAgfVxuICAgICAgICAgICAgfSxcbiAgICAgICAgICAgIHtcbiAgICAgICAgICAgICAgXCJ0eXBlXCI6IFwidGV4dFwiLFxuICAgICAgICAgICAgICBcInNob3duXCI6IGZ1bmN0aW9uICgpIHtyZXR1cm4gdGhpcy5zb3V0aFN0YXRpb24ub3Blbn0sXG4gICAgICAgICAgICAgIFwiY2xhc3NMaXN0XCI6IFtcbiAgICAgICAgICAgICAgICBcImJ0blwiXG4gICAgICAgICAgICAgIF0sXG4gICAgICAgICAgICAgIFwiYXR0clwiOiB7XG4gICAgICAgICAgICAgICAgXCJ2YWx1ZVwiOiBcIuWFs+mXreWNl+ermeS/oeaBr1wiXG4gICAgICAgICAgICAgIH1cbiAgICAgICAgICAgIH1cbiAgICAgICAgICBdXG4gICAgICAgIH1cbiAgICAgIF1cbiAgICB9XG4gIF1cbn1cblxuXG4vLy8vLy8vLy8vLy8vLy8vLy9cbi8vIFdFQlBBQ0sgRk9PVEVSXG4vLyAuL34vd2VleC1sb2FkZXIvbGliL2pzb24uanMhLi9+L3dlZXgtbG9hZGVyL2xpYi90ZW1wbGF0ZS5qcyEuL34vd2VleC1sb2FkZXIvbGliL2V4dHJhY3QuanM/dHlwZT10ZW1wbGF0ZSEuL3NyYy9wYWdlcy9pbmZvLXdpbmRvdy53ZVxuLy8gbW9kdWxlIGlkID0gMTE0XG4vLyBtb2R1bGUgY2h1bmtzID0gOSIsIm1vZHVsZS5leHBvcnRzID0ge1xuICBcImNvbnRhaW5lclwiOiB7XG4gICAgXCJwb3NpdGlvblwiOiBcInJlbGF0aXZlXCIsXG4gICAgXCJmbGV4XCI6IDEsXG4gICAgXCJiYWNrZ3JvdW5kQ29sb3JcIjogXCIjZmZmZmZmXCJcbiAgfSxcbiAgXCJtYXBcIjoge1xuICAgIFwiZmxleFwiOiAxLFxuICAgIFwicG9zaXRpb25cIjogXCJyZWxhdGl2ZVwiLFxuICAgIFwiYmFja2dyb3VuZENvbG9yXCI6IFwiI2ZmZmZmZlwiLFxuICAgIFwibWluSGVpZ2h0XCI6IDgwMCxcbiAgICBcImJvcmRlckJvdHRvbVdpZHRoXCI6IDEwLFxuICAgIFwiYm9yZGVyQm90dG9tQ29sb3JcIjogXCIjZmZmZmZmXCJcbiAgfSxcbiAgXCJtYXAtY29udHJvbFwiOiB7XG4gICAgXCJwYWRkaW5nVG9wXCI6IDIwLFxuICAgIFwibWluSGVpZ2h0XCI6IDYwMFxuICB9LFxuICBcInRpdGxlXCI6IHtcbiAgICBcIm1hcmdpbkxlZnRcIjogMjAsXG4gICAgXCJwYWRkaW5nTGVmdFwiOiAyMCxcbiAgICBcInBhZGRpbmdUb3BcIjogMTAsXG4gICAgXCJwYWRkaW5nQm90dG9tXCI6IDEwLFxuICAgIFwiZm9udFNpemVcIjogMzYsXG4gICAgXCJib3JkZXJMZWZ0V2lkdGhcIjogNixcbiAgICBcImJvcmRlckxlZnRDb2xvclwiOiBcIiMwZjg5ZjVcIixcbiAgICBcImNvbG9yXCI6IFwiIzIyMjIyMlwiLFxuICAgIFwidGV4dEFsaWduXCI6IFwibGVmdFwiXG4gIH0sXG4gIFwidGlwc1wiOiB7XG4gICAgXCJtYXJnaW5cIjogMjAsXG4gICAgXCJwYWRkaW5nXCI6IDEwLFxuICAgIFwiY29sb3JcIjogXCIjNjY2NjY2XCIsXG4gICAgXCJmb250U2l6ZVwiOiAyMFxuICB9LFxuICBcImJ0blwiOiB7XG4gICAgXCJtYXJnaW5cIjogMjAsXG4gICAgXCJwYWRkaW5nXCI6IDIwLFxuICAgIFwiYmFja2dyb3VuZENvbG9yXCI6IFwiIzFiYTFlMlwiLFxuICAgIFwiYm9yZGVyUmFkaXVzXCI6IDUsXG4gICAgXCJjb2xvclwiOiBcIiNmZmZmZmZcIixcbiAgICBcInRleHRBbGlnblwiOiBcImNlbnRlclwiLFxuICAgIFwiY3Vyc29yXCI6IFwicG9pbnRlclwiLFxuICAgIFwiZm9udFNpemVcIjogMjhcbiAgfVxufVxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vfi93ZWV4LWxvYWRlci9saWIvanNvbi5qcyEuL34vd2VleC1sb2FkZXIvbGliL3N0eWxlLmpzIS4vfi93ZWV4LWxvYWRlci9saWIvZXh0cmFjdC5qcz9pbmRleD0wJnR5cGU9c3R5bGVzIS4vc3JjL3BhZ2VzL2luZm8td2luZG93LndlXG4vLyBtb2R1bGUgaWQgPSAxMTVcbi8vIG1vZHVsZSBjaHVua3MgPSA5IiwiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgPG5hdmJhciB0aXRsZT1cIuiuvue9ruiHquWumuS5ieS/oeaBr+eql+S9k1wiPjwvbmF2YmFyPlxuICAgIDx3ZWV4LWFtYXAgY2xhc3M9XCJtYXBcIiBpZD1cIm1hcDIwMTdcIiBzZGsta2V5PXt7a2V5c319IHpvb209e3t6b29tfX0gY2VudGVyPXt7cG9zfX0+XG4gICAgICA8d2VleC1hbWFwLW1hcmtlciBzdHlsZT1cInotaW5kZXg6MTAwMFwiIGhpZGUtY2FsbG91dD1cInRydWVcIiBwb3NpdGlvbj1cInt7bWFya2VyLnBvc2l0aW9ufX1cIiBpY29uPVwie3ttYXJrZXIuaWNvbn19XCIgdGl0bGU9XCJ7e21hcmtlci50aXRsZX19XCI+PC93ZWV4LWFtYXAtbWFya2VyPlxuICAgICAgPHdlZXgtYW1hcC1tYXJrZXIgc3R5bGU9XCJ6LWluZGV4OjEwMDBcIiBoaWRlLWNhbGxvdXQ9XCJ0cnVlXCIgcG9zaXRpb249XCJ7e21hcmtlcjIucG9zaXRpb259fVwiIGljb249XCJ7e21hcmtlci5pY29ufX1cIiB0aXRsZT1cInt7bWFya2VyMi50aXRsZX19XCI+PC93ZWV4LWFtYXAtbWFya2VyPlxuICAgICAgPHdlZXgtYW1hcC1pbmZvLXdpbmRvdyAgb3Blbj1cInt7cGFsYWNlTXVzZXVtLm9wZW59fVwiIG9mZnNldD1cInt7cGFsYWNlTXVzZXVtLm9mZnNldH19XCIgcG9zaXRpb249XCJ7e3BhbGFjZU11c2V1bS5wb3NpdGlvbn19XCI+XG4gICAgICAgIDxpbmZvLXdpbmRvdyBzcmM9XCJodHRwOi8vaW1nMS52dWVkLnZhbnRoaW5rLmNuL3Z1ZWQ2ZGZkOTk4ZmMwNzM4ZjdlODhkNGI2NmJhZmM1NDdjZS5qcGVnXCIgdGl0bGU9XCJUaGUgUGFsYWNlIE11c2V1bVwiIGxvY2F0aW9uPVwiNCBKaW5nc2hhbiBGcm9udCBTdCwgRG9uZ2NoZW5nIFF1LCBCZWlqaW5nXCI+PC9pbmZvLXdpbmRvdz5cbiAgICAgIDwvd2VleC1hbWFwLWluZm8td2luZG93PlxuICAgICAgPHdlZXgtYW1hcC1pbmZvLXdpbmRvdyBvcGVuPVwie3tzb3V0aFN0YXRpb24ub3Blbn19XCIgb2Zmc2V0PVwie3tzb3V0aFN0YXRpb24ub2Zmc2V0fX1cIiBwb3NpdGlvbj1cInt7c291dGhTdGF0aW9uLnBvc2l0aW9ufX1cIj5cbiAgICAgICAgPGluZm8td2luZG93ICBzcmM9XCJodHRwOi8vaW1nMS52dWVkLnZhbnRoaW5rLmNuL3Z1ZWQyZGUzMDJlZjcyYWU5MjEzMTNhMWZhMWJiYmJkOTQ1NS5qcGVnXCIgdGl0bGU9XCJCZWlqaW5nIFNvdXRoIFJhaWx3YXkgU3RhdGlvblwiIGxvY2F0aW9uPVwiRmVuZ3RhaSwgQmVpamluZ1wiPjwvaW5mby13aW5kb3c+XG4gICAgICA8L3dlZXgtYW1hcC1pbmZvLXdpbmRvdz5cbiAgICA8L3dlZXgtYW1hcD5cbiAgICA8ZGl2IGNsYXNzPVwibWFwLWNvbnRyb2xcIj5cbiAgICAgIDx0ZXh0IGNsYXNzPVwidGl0bGVcIj5Db21wb25lbnQ6IHdlZXgtYW1hcC1pbmZvLXdpbmRvdzwvdGV4dD4gXG4gICAgICA8dGV4dCBjbGFzcz1cInRpcHNcIj7lnKjlnLDlm77kuIrmmL7npLroh6rlrprkuYnnqpfkvZM8L3RleHQ+IFxuICAgICAgPGRpdiBvbmNsaWNrPVwidG9nZ2xlTXVzXCIgY2xhc3M9XCJidG5ib3hcIj5cbiAgICAgICAgPHRleHQgaWY9XCJ7eyFwYWxhY2VNdXNldW0ub3Blbn19XCIgY2xhc3M9XCJidG5cIiA+5omT5byA5pWF5a6r5L+h5oGvPC90ZXh0PlxuICAgICAgICA8dGV4dCBpZj1cInt7cGFsYWNlTXVzZXVtLm9wZW59fVwiIGNsYXNzPVwiYnRuXCIgPuWFs+mXreaVheWuq+S/oeaBrzwvdGV4dD5cbiAgICAgIDwvZGl2PlxuICAgICAgPGRpdiBvbmNsaWNrPVwidG9nZ2xlU3RhXCIgY2xhc3M9XCJidG5ib3hcIj5cbiAgICAgICAgPHRleHQgaWY9XCJ7eyFzb3V0aFN0YXRpb24ub3Blbn19XCIgY2xhc3M9XCJidG5cIiA+5omT5byA5Y2X56uZ5L+h5oGvPC90ZXh0PlxuICAgICAgICA8dGV4dCBpZj1cInt7c291dGhTdGF0aW9uLm9wZW59fVwiIGNsYXNzPVwiYnRuXCIgPuWFs+mXreWNl+ermeS/oeaBrzwvdGV4dD5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbiAgLmNvbnRhaW5lcntcbiAgICBwb3NpdGlvbjogcmVsYXRpdmU7IFxuICAgIGZsZXg6MTsgXG4gICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjtcbiAgfVxuICAubWFwe1xuICAgIGZsZXg6IDE7XG4gICAgcG9zaXRpb246IHJlbGF0aXZlO1xuICAgIGJhY2tncm91bmQtY29sb3I6ICNmZmY7XG4gICAgbWluLWhlaWdodDogODAwO1xuICAgIGJvcmRlci1ib3R0b20td2lkdGg6IDEwO1xuICAgIGJvcmRlci1ib3R0b20tY29sb3I6ICNmZmY7XG4gIH1cbiAgLm1hcC1jb250cm9se1xuICAgIHBhZGRpbmctdG9wOiAyMDtcbiAgICBtaW4taGVpZ2h0OiA2MDA7XG4gIH1cbiAgLnRpdGxle1xuICAgIG1hcmdpbi1sZWZ0OiAyMDtcbiAgICBwYWRkaW5nLWxlZnQ6IDIwO1xuICAgIHBhZGRpbmctdG9wOiAxMDtcbiAgICBwYWRkaW5nLWJvdHRvbTogMTA7XG4gICAgZm9udC1zaXplOiAzNnB4O1xuICAgIGJvcmRlci1sZWZ0LXdpZHRoOiA2O1xuICAgIGJvcmRlci1sZWZ0LWNvbG9yOiAjMGY4OWY1O1xuICAgIGNvbG9yOiAjMjIyO1xuICAgIHRleHQtYWxpZ246IGxlZnQ7XG4gIH1cbiAgLnRpcHN7XG4gICAgbWFyZ2luOiAyMDtcbiAgICBwYWRkaW5nOiAxMDtcbiAgICBjb2xvcjojNjY2O1xuICAgIGZvbnQtc2l6ZTogMjBweDtcbiAgfVxuICAuYnRue1xuICAgIG1hcmdpbjogMjA7XG4gICAgcGFkZGluZzogMjA7XG4gICAgYmFja2dyb3VuZC1jb2xvcjogIzFiYTFlMjtcbiAgICBib3JkZXItcmFkaXVzOiA1O1xuICAgIGNvbG9yOiAjZmZmOyBcbiAgICB0ZXh0LWFsaWduOmNlbnRlcjtcbiAgICBjdXJzb3I6IHBvaW50ZXI7XG4gICAgZm9udC1zaXplOiAyOHB4O1xuICB9XG4gIFxuPC9zdHlsZT5cblxuPHNjcmlwdD5cbiAgcmVxdWlyZSgnLi4vaW5jbHVkZS9uYXZiYXIud2UnKTtcbiAgcmVxdWlyZSgnLi4vaW5jbHVkZS9pbmZvLXdpbmRvdy53ZScpO1xuICB2YXIgQW1hcCA9IG51bGw7XG4gIHRyeSB7XG4gICAgQW1hcCA9IHJlcXVpcmUoJ0B3ZWV4LW1vZHVsZS9hbWFwJyk7XG4gIH0gY2F0Y2goZXJyKSB7XG4gICAgY29uc29sZS5sb2coZXJyKTtcbiAgfVxuICB2YXIgbW9kYWwgPSByZXF1aXJlKCdAd2VleC1tb2R1bGUvbW9kYWwnKTtcbiAgbW9kdWxlLmV4cG9ydHMgPSB7XG4gICAgZGF0YToge1xuICAgICAga2V5czoge1xuICAgICAgICBoNTonZjRiOTlkY2Q1MTc1MjE0MmVjMGYxYmRjYjlhOGVjMDInLFxuICAgICAgICBpb3M6ICcnLFxuICAgICAgICBhbmRyb2lkOiAnZGI2YTk3MzE1OWNiMGMyNjM5YWQwMmM2MTdhNzg2YWUnXG4gICAgICB9LFxuICAgICAgcG9zOiBbMTE2LjM5NzQyOCwgMzkuOTA5MjNdLFxuICAgICAgem9vbTogMTEsXG4gICAgICBtYXJrZXI6IHtcbiAgICAgICAgcG9zaXRpb246IFsxMTYuMzc5Mjc4LDM5Ljg2NTM3NF0sXG4gICAgICAgIHRpdGxlOiAnQmVpamluZyBTb3V0aCBSYWlsd2F5IFN0YXRpb24nLFxuICAgICAgICBpY29uOiAnaHR0cDovL2ltZzEudnVlZC52YW50aGluay5jbi92dWVkZThmMWFlN2I0NTQyNjdkNzVjMzFjNmQ0NjgxOWI1OTcucG5nJyxcbiAgICAgIH0sXG4gICAgICBtYXJrZXIyOiB7XG4gICAgICAgIHBvc2l0aW9uOiBbMTE2LjM5NzM4OSwgMzkuOTA4NzQyXSxcbiAgICAgICAgdGl0bGU6ICdUaGUgUGFsYWNlIE11c2V1bScsXG4gICAgICAgIGljb246ICdodHRwOi8vaW1nMS52dWVkLnZhbnRoaW5rLmNuL3Z1ZWRlOGYxYWU3YjQ1NDI2N2Q3NWMzMWM2ZDQ2ODE5YjU5Ny5wbmcnXG4gICAgICB9LFxuICAgICAgcGFsYWNlTXVzZXVtOiB7XG4gICAgICAgIHBvc2l0aW9uOiBbMTE2LjM5NzM4OSwgMzkuOTA4NzQyXSxcbiAgICAgICAgb2Zmc2V0OiBbNjAsIC0xMjBdLFxuICAgICAgICBvcGVuOiBmYWxzZVxuICAgICAgfSxcbiAgICAgIHNvdXRoU3RhdGlvbjoge1xuICAgICAgICBwb3NpdGlvbjogWzExNi4zNzkyNzgsMzkuODY1Mzc0XSxcbiAgICAgICAgb2Zmc2V0OiBbNjAsIC0xMjBdLFxuICAgICAgICBvcGVuOiB0cnVlXG4gICAgICB9LFxuICAgIH0sXG4gICAgXG4gICAgbWV0aG9kczoge1xuICAgICAgdG9nZ2xlU3RhKCkge1xuICAgICAgICB0aGlzLnNvdXRoU3RhdGlvbi5vcGVuID0gIXRoaXMuc291dGhTdGF0aW9uLm9wZW47XG4gICAgICAgIC8vIG9ubHkgb25lIGluZm8gd2luZG93IGNhbiBiZSBvcGVuZWQgaW4gdGhlIG1hcFxuICAgICAgICBpZih0aGlzLnNvdXRoU3RhdGlvbi5vcGVuICYmIHRoaXMucGFsYWNlTXVzZXVtLm9wZW4pIHtcbiAgICAgICAgICB0aGlzLnBhbGFjZU11c2V1bS5vcGVuID0gZmFsc2U7ICBcbiAgICAgICAgfVxuICAgICAgfSxcbiAgICAgIHRvZ2dsZU11cygpIHtcbiAgICAgICAgdGhpcy5wYWxhY2VNdXNldW0ub3BlbiA9ICF0aGlzLnBhbGFjZU11c2V1bS5vcGVuO1xuICAgICAgICBpZih0aGlzLnBhbGFjZU11c2V1bS5vcGVuICYmIHRoaXMuc291dGhTdGF0aW9uLm9wZW4pIHtcbiAgICAgICAgICB0aGlzLnNvdXRoU3RhdGlvbi5vcGVuID0gZmFsc2U7ICBcbiAgICAgICAgfVxuICAgICAgfVxuICAgIH1cbiAgfVxuPC9zY3JpcHQ+XG5cblxuLy8gV0VCUEFDSyBGT09URVIgLy9cbi8vIC4vc3JjL3BhZ2VzL2luZm8td2luZG93LndlPzYyNDBmMTUyIiwidmFyIF9fd2VleF90ZW1wbGF0ZV9fID0gcmVxdWlyZShcIiEhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL2pzb24uanMhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL3RlbXBsYXRlLmpzIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP3R5cGU9dGVtcGxhdGUhLi9pbmZvLXdpbmRvdy53ZVwiKVxudmFyIF9fd2VleF9zdHlsZV9fID0gcmVxdWlyZShcIiEhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL2pzb24uanMhLi8uLi8uLi9ub2RlX21vZHVsZXMvd2VleC1sb2FkZXIvbGliL3N0eWxlLmpzIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9leHRyYWN0LmpzP2luZGV4PTAmdHlwZT1zdHlsZXMhLi9pbmZvLXdpbmRvdy53ZVwiKVxudmFyIF9fd2VleF9zY3JpcHRfXyA9IHJlcXVpcmUoXCIhIS4vLi4vLi4vbm9kZV9tb2R1bGVzL3dlZXgtbG9hZGVyL2xpYi9zY3JpcHQuanMhYmFiZWwtbG9hZGVyP3ByZXNldHNbXT0vVXNlcnMvYWxpLTEzMDI1N24vd3d3L2FwcC9ub2RlX21vZHVsZXMvYmFiZWwtcHJlc2V0LWVzMjAxNSZwcmVzZXRzPS9Vc2Vycy9hbGktMTMwMjU3bi93d3cvYXBwL25vZGVfbW9kdWxlcy9iYWJlbC1wcmVzZXQtZXMyMDE1JnBsdWdpbnNbXT0vVXNlcnMvYWxpLTEzMDI1N24vd3d3L2FwcC9ub2RlX21vZHVsZXMvYmFiZWwtcGx1Z2luLXRyYW5zZm9ybS1ydW50aW1lJnBsdWdpbnM9L1VzZXJzL2FsaS0xMzAyNTduL3d3dy9hcHAvbm9kZV9tb2R1bGVzL2JhYmVsLXBsdWdpbi10cmFuc2Zvcm0tcnVudGltZSZjb21tZW50cz1mYWxzZSEuLy4uLy4uL25vZGVfbW9kdWxlcy93ZWV4LWxvYWRlci9saWIvZXh0cmFjdC5qcz9pbmRleD0wJnR5cGU9c2NyaXB0cyEuL2luZm8td2luZG93LndlXCIpXG5cbl9fd2VleF9kZWZpbmVfXygnQHdlZXgtY29tcG9uZW50L2luZm8td2luZG93JywgW10sIGZ1bmN0aW9uKF9fd2VleF9yZXF1aXJlX18sIF9fd2VleF9leHBvcnRzX18sIF9fd2VleF9tb2R1bGVfXykge1xuXG4gICAgX193ZWV4X3NjcmlwdF9fKF9fd2VleF9tb2R1bGVfXywgX193ZWV4X2V4cG9ydHNfXywgX193ZWV4X3JlcXVpcmVfXylcbiAgICBpZiAoX193ZWV4X2V4cG9ydHNfXy5fX2VzTW9kdWxlICYmIF9fd2VleF9leHBvcnRzX18uZGVmYXVsdCkge1xuICAgICAgX193ZWV4X21vZHVsZV9fLmV4cG9ydHMgPSBfX3dlZXhfZXhwb3J0c19fLmRlZmF1bHRcbiAgICB9XG5cbiAgICBfX3dlZXhfbW9kdWxlX18uZXhwb3J0cy50ZW1wbGF0ZSA9IF9fd2VleF90ZW1wbGF0ZV9fXG5cbiAgICBfX3dlZXhfbW9kdWxlX18uZXhwb3J0cy5zdHlsZSA9IF9fd2VleF9zdHlsZV9fXG5cbn0pXG5cblxuXG4vLy8vLy8vLy8vLy8vLy8vLy9cbi8vIFdFQlBBQ0sgRk9PVEVSXG4vLyAuL3NyYy9pbmNsdWRlL2luZm8td2luZG93LndlXG4vLyBtb2R1bGUgaWQgPSAxMTdcbi8vIG1vZHVsZSBjaHVua3MgPSA5Il0sInNvdXJjZVJvb3QiOiIifQ==